name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master
      - main

concurrency: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.10
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: 'false'
        with:
          configurationFile: ./renovate.json
          token: '${{ secrets.RENOVATE_GITHUB_TOKEN }}'
